"""add planned routes and deviation states

Revision ID: 171e4dfe077f
Revises: 79bc729a5ce9
Create Date: 2026-09-28 03:23:32.710597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '171e4dfe077f'
down_revision: Union[str, Sequence[str], None] = '79bc729a5ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planned_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('route_points', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planned_routes_organization_id'), 'planned_routes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_planned_routes_trip_id'), 'planned_routes', ['trip_id'], unique=True)
    op.create_table('route_deviation_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('currently_deviated', sa.Boolean(), nullable=False),
    sa.Column('last_distance_meters', sa.Float(), nullable=True),
    sa.Column('threshold_meters', sa.Float(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_alert_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_deviation_states_trip_id'), 'route_deviation_states', ['trip_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_deviation_states_trip_id'), table_name='route_deviation_states')
    op.drop_table('route_deviation_states')
    op.drop_index(op.f('ix_planned_routes_trip_id'), table_name='planned_routes')
    op.drop_index(op.f('ix_planned_routes_organization_id'), table_name='planned_routes')
    op.drop_table('planned_routes')
    # ### end Alembic commands ###
