"""enforce one active trip per vehicle

Revision ID: 79bc729a5ce9
Revises: ba5f4ee80ba6
Create Date: 2026-09-28 00:39:57.375696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79bc729a5ce9'
down_revision: Union[str, Sequence[str], None] = 'ba5f4ee80ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_trips_active_vehicle', 'trips', ['vehicle_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_trips_active_vehicle', table_name='trips', postgresql_where=sa.text("status = 'ACTIVE'"))
    # ### end Alembic commands ###
